baseURL = "https://livingfluently.com/"
languageCode = "en-us"
title = "Living Fluently"
theme = "hugo-theme-cactus"
copyright = "David Lennard" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

css = ["css/custom.css"]

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writing"
url = "/posts"
weight = 2

[[menu.main]]
name = "Start Here"
url = "/StartHere"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hey, welcome 🤲🍵. This is my project to create a craft-based approach to personal growth, in theory and practice. I'm also journaling publicly as I navigate the landscape of my own experience, participating in the collective effort to find paths forward. "
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/dave_lennard_/"
  [[params.social]]
    name = "Discord"
    link = "https://discordapp.com/users/9151/"
  [[params.social]]
    name = "email"
    link = "david.aaron.lennard@gmail.com"  # no need for "mailto:" in the head
